### ISSUE TITLE
Hi when i run script i have error. Why?

### ISSUE THREAD

**Issue by sumrakx** [zhisme/hwm_worker#1]
$ bin/run
C:/RailsInstaller/Ruby2.3.3/lib/ruby/2.3.0/open-uri.rb:37:in `initialize': No such file or directory @ rb_sysopen - logs/worker.log (Errno::ENOENT)
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/2.3.0/open-uri.rb:37:in `open'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/2.3.0/open-uri.rb:37:in `open'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/2.3.0/logger.rb:711:in `create_logfile'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/2.3.0/logger.rb:705:in `rescue in open_logfile'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/2.3.0/logger.rb:702:in `open_logfile'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/2.3.0/logger.rb:695:in `set_dev'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/2.3.0/logger.rb:635:in `initialize'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/2.3.0/logger.rb:353:in `new'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/2.3.0/logger.rb:353:in `initialize'
        from C:/Users/sunDY/Desktop/hwm_worker/lib/helpers/work_logger.rb:7:in `new'
        from C:/Users/sunDY/Desktop/hwm_worker/lib/helpers/work_logger.rb:7:in `<class:WorkLogger>'
        from C:/Users/sunDY/Desktop/hwm_worker/lib/helpers/work_logger.rb:6:in `<top (required)>'
        from C:/Users/sunDY/Desktop/hwm_worker/lib/hwm_worker/login.rb:2:in `require'
        from C:/Users/sunDY/Desktop/hwm_worker/lib/hwm_worker/login.rb:2:in `<top (required)>'
        from C:/Users/sunDY/Desktop/hwm_worker/lib/hwm_worker/runer.rb:1:in `require'
        from C:/Users/sunDY/Desktop/hwm_worker/lib/hwm_worker/runer.rb:1:in `<top (required)>'
        from C:/Users/sunDY/Desktop/hwm_worker/lib/hwm_worker.rb:3:in `require'
        from C:/Users/sunDY/Desktop/hwm_worker/lib/hwm_worker.rb:3:in `<top (required)>'
        from bin/run:4:in `require'
        from bin/run:4:in `<main>'

**Comment by zhisme** [comment]
well, you need to create it by hand.
```
touch hwm_worker/logs/worker.log
```
